on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://pypi.org/p/weiser-ai
    permissions:
      id-token: write
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Match the Python version in pyproject.toml

      # Install PDM
      - name: Install PDM
        run: python -m pip install --upgrade pip pdm

      # Install build dependencies
      - name: Install build dependencies
        run: pdm install --prod

      # Build the package
      - name: Build package
        run: pdm build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
